// Errors
export const TEACHER_PENCIL_ID_INVALID = "TEACHER_PENCIL_ID_INVALID";
export const TEACHER_NOT_SCHEDULED = "TEACHER_NOT_SCHEDULED";
export const APPOINTMENT_IN_PAST = "APPOINTMENT_IN_PAST";
export const APPOINTMENT_IN_FUTURE = "APPOINTMENT_IN_FUTURE";

// Success
export const TEACHER_NOT_YET_SCHEDULED = "TEACHER_NOT_YET_SCHEDULED";
