// Errors
export const TEACHER_EMAIL_INVALID = "TEACHER_EMAIL_INVALID";
export const TEACHER_EMAIL_NOT_SCHEDULED = "TEACHER_EMAIL_NOT_SCHEDULED";
export const APPOINTMENT_IN_PAST = "APPOINTMENT_IN_PAST";
export const APPOINTMENT_IN_FUTURE = "APPOINTMENT_IN_FUTURE";
